### ISSUE TITLE
Find/create workflow for this repo to `npm publish` when it merges a PR

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#105]
https://devops.stackexchange.com/a/10115

[Also ensure our pre-releases don't get pulled with npm install @suffolkLITLab/alkiln] #502

**Comment by plocket** [comment]
Or maybe bump and publish branch on push and bump and publish `main` on merge, dealing with bumping beyond already published versions... This sounds like a tricky wicket.

**Comment by plocket** [comment]
Could also be expanded to edit the version the package.json that gets pushed so that it has the right version in it.

We can probably start using relative semver now that we have our first stable version.

**Comment by plocket** [comment]
If you feel up to taking this one on, @berit , we'd be quite grateful. If that works, go ahead and assign yourself to the issue.

**Comment by plocket** [comment]
Someone suggested using git tags/releases. I'm not really sure how this works. If we do that, we would also need to avoid editing the version in package.json:

> it's pretty well established across stacks that if you want to drive your versioning from git tagging/releases, keeping versions inside the content too becomes very problematic and it's best to inject versions during your build process 

Version changes would not be committed at all:

> [let] git tagging drive your versioning. Just leave a placeholder version in package.json, and use npm version to set it from the tag right before publishing with the workflow hooked up to git tags getting pushed. If you're going to use git tags and automation it ends up not really making sense to track versions in both the git tag AND the contents of your repo that gets tagged

There apparently some UI in github to do this. Not sure how it would work locally exactly. Or on github for that matter. This was a link that was provided for clarification: https://github.com/JarvusInnovations/hologit/blob/develop/.github/workflows/publish-npm.yml

**Comment by plocket** [comment]
This is what we're looking at now: https://www.npmjs.com/package/release-it/v/14.6.2. I tried it out locally and it's looking pretty good. Not sure exactly how we'd set it up to be automated as it pushes, but at the very least it will make it easier to do locally. Maybe for automation there's a way we can differentiate between merges and pushes or something.

**Comment by plocket** [comment]
semver discussion of refactoring and whether to bump version for it: https://github.com/semver/semver/issues/215

I think we'll bump patch on refactoring. The argument I found compelling for that: refactoring could accidentally introduce bugs and the bumped version number would allow dependents to deal with that appropriately.

**Comment by plocket** [comment]
We might want to push tags to GitHub depending on what we do with [freezing the package-lock.json](https://github.com/SuffolkLITLab/ALKiln/issues/614#issuecomment-1244733632).

We might be able to at least use this action that outputs the release number: https://github.com/MeilCli/bump-release-action/blob/master/README.md#output.

We also need to use the output to :
1. Update the developer's package.json and package-lock.json. How do we do this? It has to come before the action (so the changes get published to npm with the bump), but the packages have to use the same version as the action creates. Maybe we can feed in a specific version to the action manually after having created it for the files. Prone to error, but what else can we do? Is it possible to automate? We then do the action, adding its commits to the specific branch where we updated those files? [Maybe look into the 'files' section (under the [bump section](https://github.com/MeilCli/bump-release-action#bump) since files link doesn't work). I don't think it'll handle installing the package, though, to create package-lock.json.]
3. Push the new GitHub tag. The bump action might have this built in. See `tag-prefix` in their bump.yml in the README. It seems to want to push to a new branch that can make a PR. Maybe that's the best way to go. Not sure how it lines up with npm, especially if it doesn't get merged.
4. Ideally, update the CHANGELOG. Probably before the action so it can be part of the same commit. Maybe it's possible to do this with some clever string manipulation, though only if people are consistent with how they write the changelog, which seems very fragile. Read more below about why we'd want to do it at the same time.

I'm not sure what we'll do about the changelog because its new version entry really shouldn't be fully filled out without knowing the npm version at the same time or mistakes and confusion might ensue. I wish we could use the changelog to control what version is published. If anyone has ideas or can find a solution, that could be a good bonus.

On the other hand, maybe our tag commits will be our changelog, though we'll lose the benefit of all the past changelogs. Can they be multi-line? Detailed? Have links? Do you know anything about this @BryceStevenWilley ?

Experiments:
- Can we have a multiline commit/tag message when we run this action? (to act as a changelog)
- Is it possible to add this as a commit to a pre-existing branch (where we'd have updated the developer's files)?
- (may not need this  info, so not a priority right now) Is it possible to push to the default branch instead of a non-default branch?

**Comment by plocket** [comment]
https://github.com/MeilCli/bump-release-action doesn't have a lot of stars and I can't see how many people are using it. I'm looking at their marketplace page too: https://github.com/marketplace/actions/bump-version-and-publish-release-action. It seems to have a ton of commits, though, and have a few more recent commits. We can try looking for another one...

**Comment by plocket** [comment]
I've gotten some feedback from a place:
- a package lock is dev-only
- a package’s consumers don’t use the lockfile
- a package should ALWAYS use ranges

I'm not sure if "a package’s consumers don’t use the lockfile" means that it's impossible or just that it's generally not a good idea. Is this endeavor possible?

**Comment by plocket** [comment]
Apparently you can't publish to npm through an action anymore because of two-factor authentication... I guess we may need a script to run locally instead. Any other ideas?

**Comment by plocket** [comment]
From @BryceStevenWilley 's [comment in the accidental issue](https://github.com/SuffolkLITLab/ALKiln/issues/502#issuecomment-1247038684).

The scope of this is a bit bigger than I had anticipated; I hadn't thought that we would make the action change code at all, that it would just take an existing commit and package / publish it, and make a Github release. Still might be all doable, but just a lot more than I thought, and would required IMO a bit more testing to make sure the action works as anticipated.

https://github.com/MeilCli/bump-release-action seems like a decent package, the developer is responsive to the few issues they've had on the repo. I don't think stars is a great metric to lean on.

> I've gotten some feedback from a place: a package lock is dev-only

Looking back through old discussions, it looks like [shrinkwrap](https://docs.npmjs.com/cli/v8/configuring-npm/npm-shrinkwrap-json) is what we want: it is explicitly for publishing, so none of the feedback from your source applies, since I think that feedback is mostly for publish packages as libraries, not as a separate application, like we are. I think we've had this discussion before, in https://github.com/SuffolkLITLab/ALKiln/discussions/532.

> Apparently you can't publish to npm through an action anymore because of two-factor authentication

Is that something you directly ran into, or something you heard about, I can't tell from the comment? From https://docs.npmjs.com/about-two-factor-authentication, we should be able to set 2FA to `admin` only, so we can still publish packages without need 2FA.

**Comment by plocket** [comment]
> Looking back through old discussions, it looks like [shrinkwrap](https://docs.npmjs.com/cli/v8/configuring-npm/npm-shrinkwrap-json) is what we want

Great find! I did think we'd discussed this somewhere before, but couldn't find it.

> Is that something you directly ran into, or something you heard about

Something I heard about, my bad.

**Comment by plocket** [comment]
After more conversations with others, it looks like we do need to stay away from shrinkwrap. [The situation we have on our hands has changed since #532.] Instead, once we create the package.json and package-lock.json files in our repo, _all_ of our users' dependency versions are frozen, including ALKiln and its dependencies. That means ALKiln itself doesn't need to freeze anything. [And in fact maybe shouldn't freeze anything for fear of conflicting?] The only thing that matters for freezing, from what I can tell, is that we make the users' package-lock.json and make sure we use `npm ci` for our users.

We can use `npm ci` for ourselves too, but that's a different question. I think. I think we can also just keep `.gitignore`ing our package-lock.json

**Comment by BryceStevenWilley** [comment]
> it looks like we do need to stay away from shrinkwrap

Mind mentioned what reasoning your contacts are giving? I would have agreed with your current approach, but it seems like shrink wrap was intentionally made to solve the problem we're having. Specifically, with shrinkwrap, we don't need to make a `package-lock.json` for users by just downloading arbitrary github files from our repo, an approach that still seems precarious.

> I think we can also just keep .gitignoreing our package-lock.json

Just realized that we do this: isn't the main technical action item is this issue is making users download the `package-lock.json` directly from this repo? 

If we do go with the shrinkwarp solution, I still think that we still need the `package-lock.json`: the reasoning for removing the file listed in [this commit](https://github.com/SuffolkLITLab/ALKiln/commit/7328c8479606603bb8701fdae775dbee5b3283d3) was so "our tests behave more like our user's tests", but that's what shrinkwrap is trying to fix, more appropiately, but forcing users dependencies to match ours.

**Comment by plocket** [comment]
Thanks for those comments. I've struggled with this a bit too and keep losing the thread. The questions you asked might help us articulate this better.

> Specifically, with shrinkwrap, we don't need to make a package-lock.json for users by just downloading arbitrary github files from our repo, an approach that still seems precarious.

Our own package isn't useful to them. For example, it doesn't install itself, so our package-lock.json wouldn't install `alkiln` for our users. We need to create and freeze their package-lock.json, not ours. I agree it's a weird and backwards way to do it, but half of action.yml is now a weird backwards way of doing this.

> arbitrary github files from our repo

Just to be clear, they're not ones we build by hand or something crazy like that. We'll use `npm install` to create that package-lock.json, it'll just be in a folder, not in our root. You can have nested node projects and I believe they don't interfere with each other, at least from what I've tried so far.

> isn't the main technical action item in this issue is making users download the package-lock.json directly from this repo

Hmm, I think not. I think that's answered by my above comment, but to restate - our package-lock.json doesn't serve our users' needs. It doesn't contain all the packages our users need.

Does any of that make sense?

**Comment by plocket** [comment]
`npm publish` automation article: https://hackernoon.com/publish-npm-packages-using-github-actions-a-how-to-guide-q31c34fg

**Comment by plocket** [comment]
Trying to layout and justify the flow I think we need, either manual or automated.

Because most of our users don't have the resources to manage a package.json or package-lock.json of their own, we're storing and updating those files for our users. We'll contain them in a folder called "user_files". When the user runs their workflow and uses our action, we will copy the files from "user_files" into the root of their repo temporarily to run the tests. When we install the packages for their tests, we will use `npm ci` (instead of `npm install`) so that their packages will install using the package-lock.json that we've created for them.

The proposed flow is:

1. Possibly manually update our CHANGELOG
2. Bump our alkiln package
3. Maybe commit. npm doesn't require committing, but I'm not sure how this will affect later steps. [If we commit, I'm not sure what happens with tags.]
4. npm publish alkiln so that later we can update the files that our users' workflow will use
5. Wait till npm publish has taken effect (it's not always immediate)
6. Update **users'** package.json and package-lock.json files by `npm install`ing the alkiln version we just published
7. Bump and commit
8. Release to GitHub tag on a new branch and push
9. PR 
10. Merge the new branch
11. Possibly publish on npm again [somewhere after changing user files], even though our users' files will not refer to this newly published version. Our users' files don't need to refer to this particular new version. The only thing that really cares about the reference in users' files is the GitHub action. The GitHub action will have access to the updated user files whether they're published on npm or not. Also, it's impossible to keep the users' files "up to date" with themselves on npm. It's an infinite loop.

There will probably have to be some manual steps. For example, waiting till npm has properly published the new version of alkiln. (The following has not been fully discussed yet) We might want to keep the changelog around and edit it manually. That said, doing all these steps manually every time the package needs to release a new version is a lot of work and some of it pretty fiddly.

Note: We discussed copying alkiln's package-lock.json to give to our users' workflows, but that won't work. Our package-lock.json doesn't contain alkiln itself. I don't think it can. alkiln also has many requirements that our users don't need.

Needs clarification? Questions? Suggestions? @BryceStevenWilley ?

**Comment by BryceStevenWilley** [comment]
Assuming that we want to go with `npm-shrinkwrap.json` instead of `package-lock.json` (see longer discussion in https://github.com/SuffolkLITLab/ALKiln/issues/614), I think this would be the full release process:

1. Make sure that the repo is ready to release:
    * CHANGELOG is up-to-date, keeping the "unreleased" section title as is
    * shrinkwrap is as we want it (see longer description below: shrinkwrap doesn't have to be tied to the release process directly)
    * haven't yet bumped the version string.
2. These steps could be encapsulated in a Github action:
    1. Bump version string ~and commit~
    2. Change the Unreleased section in the CHANGELOG to the new version string, and commit
    3. Make a PR that is only doing a release. Wait for tests to pass (using npm ci, which works with either package-lock or shrinkwrap).
    4. Merge the PR (if these steps are still manual, the PR is less important. It's only important if there's something that the Github action has messed up, and takes little time to review).
3. These steps should be made into a different Github Action, that could be trigged by making a Github Release, or automatically when the above PR is merged
    1. Make the Github Release: copy from the CHANGELOG, otherwise use the Github auto-filled description, the canonical source should always be the CHANGELOG.
    2. Making the Github Release make a Git tag
    3. NPM publish

Overall the process can eventually be 3 manual steps, 1 being a "yep", everything's ready to go, 2 starting the Release Action manually, and 3 being merging the Release PR. In this case, shrinkwrap really only needs to be run when we add a dependency, or we want to manually update an existing dependency to a newer version. I don't think we need to run shrinkwrap each time we make a release.

**Comment by plocket** [comment]
I have more to think about here. In the meantime, some tiny thoughts about possibly tiny changes that I just don't want to forget.

- 2.i. and 2.ii. might be switched so that the CHANGELOG and version bump will get committed at the same time. I think it should be possible to make the versions consistent to each other.
- Why wait to `npm publish` at the end? We can save some work by including it in the automation of step 2. If we need to make changes, we'll have to bump the version again anyway. At that point we can publish again, maybe manually.
- May have to do more research on my assumptions here: If we make the GitHub Release tag with `push` with `--follow-tag` (I believe), there'll be less room for error because it'll use the npm version automatically. I'm not sure what that will do for the Release message, though.

**Comment by BryceStevenWilley** [comment]
> 2.i. and 2.ii. might be switched so that the CHANGELOG and version bump will get committed at the same time

:+1:, edited

> Why wait to npm publish at the end? We can save some work by including it in the automation of step 2

Because step 2 ends with merging the PR. I don't think we should publish until after that release PR is merged to the repo.

> If we make the GitHub Release tag with push with --follow-tag (I believe), there'll be less room for error because it'll use the npm version automatically

I don't think I differentiated the steps well enough here, and I think concepts are getting muddled, so for my clarity: making a Github Release ([Assebly Line repo for example](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/releases)) is just a manual step. If/when we want to replace that manual step, we would make an automated action that would:
* make a git annotated tag ([AL example here](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/releases/tag/v2.15.0))
* push said git annotated tag to github

[`--follow-tags`](https://git-scm.com/docs/git-push#Documentation/git-push.txt---follow-tags) just pushes tags automatically, but since we creating the tag in the same workflow file, I don't think it makes the workflow file any simpler.

> I'm not sure what that will do for the Release message, though.

With this process (i.e. starting the release process with a manually started action), we're able to still maintain the in-repo `CHANGELOG`, so IMO to reduce duplication, we can add a link to the latest `CHANGELOG` file instead of filling out an entire git annotated tag or filling in an entire Github Release with information that's duplicated in the CHANGELOG.

**Comment by plocket** [comment]
Thanks, I'll think about that. One more thing for now and sorry I missed it before:

> 2.iii.Make a PR that is only doing a release.

What does this mean by "release". I think this isn't referring to npm publishing or GitHub Release, right?

**Comment by BryceStevenWilley** [comment]
> What does this mean by "release"

Sorry, yeah, a wordy-er version would be "Make a PR that only contains release-related changes (the bumped version and changelog updates)."
