### ISSUE TITLE
Proposal: Procedure for merging PRs to our default branch regarding version numbers

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#123]
# 1:
1. PR should have pre-release version number format based on its base version (`x.x.x-feature.n`) (See pre-release here: https://semver.org/spec/v2.0.0.html#spec-item-9). That is, if you start development with `1.2.3`, your development code version numbers should extend that version number like this: `1.2.3-hotfix-scope.1`. (I think that's how it works to maintain proper [precedent so pre-release versions don't override release versions](https://semver.org/spec/v2.0.0.html#spec-item-11))
1. PR should link to tests showing successful expected behavior (even if that involves showing errors)
1. Review PR
1. Merge PR when appropriate
1. Make sure there is no issue that someone has made about them updating the version number. If there is one, wait until that's resolved.
1. If you had to wait, I don't even know. This is terrible.
1. Make an issue with the version number you will update to
1. Increment version
1. Update files to push (like with the correct package version)
1. Publish version
1. Commit and merge (or PR with?) those changes

Devs coordinate on those final merged version numbers. Should one person be the steward of tracking those? That's not super flexible.

When merging a PR, you make an issue for the version number you will be publishing after merging.

# 2:
1. PRs have feature versions as described
1. PR links to test
1. Review PR
1. Coordinate with others - pull, update version number, update dependent package.json if needed (usually just on major versions), publish, push to PR branch, merge PR

**Comment by niharikasingh** [comment]
Does every PR get its own minor version package update, or should that only happen more rarely (say, once a month)?

**Comment by plocket** [comment]
Each bug fix gets its own version number for sure (Patch: x.x.n)

I don't know about Minor versions because I don't know if we'll be counting refactoring as minor versions. It seems like something that wouldn't need a version number change, but we don't really know what new behavior we might accidentally be introducing. Also, does that mean refactoring is a patch or a minor? If a minor, I guess it's not a new feature so it doesn't need to be updated.

Without a new version number, dependents will not be using that code. Does that help?

**Comment by plocket** [comment]
Then do we give refactoring a feature number? Because then master has a pre-release feature number. Which doesn't seem great.
