### ISSUE TITLE
The nav bar Back Button Is Not Visible

### ISSUE THREAD

**Issue by Sweta-Alla** [SuffolkLITLab/ALKiln#145]
On the "YOUR FORM IS READY!" page I believe.

<img width="1440" alt="Screen Shot 2021-01-29 at 6 42 48 PM" src="https://user-images.githubusercontent.com/62673130/106338598-29a61780-6262-11eb-82ca-10db97d67962.png">

**Comment by plocket** [comment]
I think it's probably on all the pages.
