### ISSUE TITLE
Apostrophes in statements can create Unimplemented error

### ISSUE THREAD

**Issue by blakew** [SuffolkLITLab/ALKiln#152]
"Then I can't continue" statement has an apostrophe which can be represented by different characters. Suggest adding a "Then I cannot continue" syntax (without apostrophe) and/or including all types of apostrophes.

**Comment by rpigneri-vol** [comment]
The main idea is to replace the single quote (') with the apostrophe (the fancy Unicode character that Word uses).

**Comment by plocket** [comment]
Rather, to include a match for the apostrophe as well as the single quote, and possibly "cannot"

**Comment by plocket** [comment]
This is one example of a step that needs adjustment: https://github.com/plocket/docassemble-cucumber/blob/main/lib/steps.js#L420
