### ISSUE TITLE
How do we clarify table fixtures?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#188]
The amount of repetition in this test setup makes me slightly nervous that copy+paste errors while writing the test could result in spurious test failures. Is it possible to write tests where the input is just the original table (as the developer would write it) and it gets compared to the processed version of the new-style table (again, as the developer would write it)?

_Originally posted by @niharikasingh in https://github.com/plocket/docassemble-cucumber/pull/186#discussion_r603777496_

**Comment by plocket** [comment]
Hmm. First, you have a good point. The complexity is unfortunate and I did struggle with it a bit. Secondly, there are a couple problems with this:
1. The conversion of the original table is never going to look exactly the same as if we were to write it ourselves now. It will function the same way because of which column values are or aren't used in the rest of the code, but they won't have exactly the same values.
2. I'm just not sure how we'd do it. We'd have to convert them to strings to make them look like the cucumber tables. Even the original one. It comes in as an object or array, not as a string.

Would it be sufficient if we just formatted these objects to be more visually clear? That is, to look more similar to a table than they do now?

**Comment by niharikasingh** [comment]
I think the more closely the test input resembles what people actually write in cucumber test files, the more useful the tests. If the closest we can get (without undue effort) is to make the input look more similar to the table, that's fine.

**Comment by plocket** [comment]
Maybe we can arrange spacing so it looks like the different props are in three columns.
