### ISSUE TITLE
Test action button that just has a URL, not a da event

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#200]
Don't throw an error. Not sure what the encoded name would be, though.

**Comment by BryceStevenWilley** [comment]
I don't know if this is the exact purpose of this issue, but I couldn't find a closer one. I'm trying to just press an action button, that has a specific `url_ask` passed in. 

Without using the manual [`id_tag` attribute of `action_button_html`](https://docassemble.org/docs/functions.html#action_button_html) there's no easy way to find a given button. Here's an example of an `action_button_html` gets you by default:
```py
${ action_button_html(url_ask(
    [{'recompute': ['create_attorney', 'show_resp']}]),
    label="Create Attorney") }
```

```html
<a data-linknum="346" 
  data-embaction="eyJhY3Rpb24iOiAiX2RhX2ZvcmNlX2FzayIsICJhcmd1bWVudHMiOiB7InZhcmlhYmxlcyI6IFt7ImFjdGlvbiI6ICJfZGFfdW5kZWZpbmUiLCAiYXJndW1lbnRzIjogeyJ2YXJpYWJsZXMiOiBbImNyZWF0ZV9hdHRvcm5leSIsICJzaG93X3Jlc3AiXX19LCB7ImFjdGlvbiI6ICJfZGFfY29tcHV0ZSIsICJhcmd1bWVudHMiOiB7InZhcmlhYmxlcyI6IFsiY3JlYXRlX2F0dG9ybmV5IiwgInNob3dfcmVzcCJdfX1dfX0" 
  href="/run/EFSPIntegration/admin_interview/?action=eyJhY3Rpb24iOiAiX2RhX2ZvcmNlX2FzayIsICJhcmd1bWVudHMiOiB7InZhcmlhYmxlcyI6IFt7ImFjdGlvbiI6ICJfZGFfdW5kZWZpbmUiLCAiYXJndW1lbnRzIjogeyJ2YXJpYWJsZXMiOiBbImNyZWF0ZV9hdHRvcm5leSIsICJzaG93X3Jlc3AiXX19LCB7ImFjdGlvbiI6ICJfZGFfY29tcHV0ZSIsICJhcmd1bWVudHMiOiB7InZhcmlhYmxlcyI6IFsiY3JlYXRlX2F0dG9ybmV5IiwgInNob3dfcmVzcCJdfX1dfX0" 
  class="btn btn-sm btn-success btn-darevisit">
    Create attorney
</a>
```
Where the `data-embaction` is `{\"action\": \"_da_force_ask\", \"arguments\": {\"variables\": [{\"action\": \"_da_undefine\", \"arguments\": {\"variables\": [\"create_attorney\", \"show_resp\"]}}, {\"action\": \"_da_compute\", \"arguments\": {\"variables\": [\"create_attorney\", \"show_resp\"]}}]}}"` encoded into base64.

Related conversation here: https://cfb-public.slack.com/archives/CQ8RWCH17/p1648761462993049

**Comment by plocket** [comment]
This issue was actually a much simpler one about plain old urls for action buttons. This description is much more interesting and I'm alright sharing this issue for both of these if you are.

Easiest solution for us is to require folks to use an `id_tag`. Beyond that, I don't know all the possible configurations that `action_button_html(url_ask())` can construct, but it's json and we could parse it. For example, the innermost property I see in the above is `["create_attorney", "show_resp"]`. That seems like something that a user could provide, though we'd have to think about what that sentence would look like.
