### ISSUE TITLE
Discuss: Playwright vs. Puppeteer vs. Cypress

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#212]
Status:
~Cypress~: rejected
Playwright: ?
Puppeteer: ?

They seem to have very similar syntax and it might be super easy to switch.

Old article about it: https://blog.logrocket.com/playwright-vs-puppeteer/

From what I'm picking up, playwright (by Microsoft) supports tests for Chrome, Firefox, and Webkit (Safari), but the latter two in slightly customized ways. Puppeteer is made by Google does Chrome and Firefox.

Playwright would let us test in more browsers when we're ready for that. Also, though this may seem like a downside, it's newer and less used. That may or may not be inconvenient for us, but could help improve competition between the two.

Edit: Migrating from one to the other: https://playwright.dev/docs/puppeteer

Edit:

Things we want to be able to do:

- Pass on failures for our own internal tests and for warnings instead of errors, like failing accessibility, though we might be able to handle that with try/catch
- Hide sensitive information in logs and in videos
- Download files without waiting for the whole length of the timeout
- Control timeouts
- Manipulate the DOM directly
- Log to the console
- Create our own report
- Will add more as I recall items

**Comment by plocket** [comment]
Cypress allows GitHub actions to provide the test recording it can create out of the box: https://github.com/cypress-io/github-action#tag-recordings. I'm not yet sure if it gives the whole experience you get locally and I don't know if you can chose to redact content for certain tests, but still something to consider.

I've tried to find that for Playwright, but haven't found anything built in for that.

Edit:
Starting to do research on hiding sensitive info in Cypress. Something about a `log` option maybe.
- https://glebbahmutov.com/cypress-examples/recipes/hide-email.html#intercept-the-form-submission-network-call
- https://glebbahmutov.com/blog/keep-passwords-secret-in-e2e-tests/

[Hack for logging](https://j1000.github.io/blog/2022/10/27/enhanced_cypress_logging.html) that make me a bit leery of what we may have to do to manipulate things the way we want.

**Comment by BryceStevenWilley** [comment]
Looked into this a bit more, (following the bread crumbs of PDF comparison -> downloading files -> playwright might be better). My only additional thoughts for these choices are that Cypress doesn't seem like it's a good fit for Kiln. From https://docs.cypress.io/guides/references/trade-offs:

> The trade-off here is that doing everything in the browser (basically all of your tests) is a much better experience in Cypress. But doing things outside of the browser may take a little extra work.

We'd have to change a lot about how we access and download people's feature files if we switched.

> Because Cypress runs in the browser, it will never have multi-tabs support.

It goes on to give a ton of work arounds about opening things in new tabs, like directly visiting the `href` of a link, or modifying the HTML of a page. Which is the exact thing that we're trying to avoid doing in puppeteer, haha.

> Cypress does not support controlling more than 1 open browser at a time.

Less of an issue currently, but this would throw a wrench into our idea of running tests in parallel.

Cypress is really powerful, but I think that power is useful for really JS heavy sites, which DA isn't (yet, I'll believe that a react version of DA is coming when I see it). The tools we currently have (downloading HTML, screenshots, and videos) are good enough to debug issues, and I don't think more powerful browser replay-ability would be accessibly to most DA developers.

I'll try looking into playwright more, and seeing what all we'd need to change to get that to work.
