### ISSUE TITLE
Allow story tables to exclude headers

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#257]
In `normalizeTable` in `scope.js`, add this code back in, replacing how it's currently trying to detect a lack of headers. Right now that function gets basically `the_table.hashes()`, but if we use the plain cucumber data we can possibly check for the values of the first row and see if they're the headers we're looking for. Testing for just an array (as below) is not enough.

```js
    // If table doesn't have headers, give it headers
    // No repos we know of has used the array version of this table as of 03/27/21,
    // so we shouldn't need to support the old formatted tables in here.
    let sample = var_data[0];
    let var_data = var_data;
    if ( Array.isArray( sample )) {
      let rows = raw_var_data.raw();
      var_data = rows.map(( row ) => {
        let result = { var: row[0], value: row[1], checked: row[2] };
        if ( row[3] ) { result.sought = row[3]; }  // So original format row doesn't accidentally get a sought var col
        return result;
      });
    }
```

**Comment by plocket** [comment]
The code above may not be sufficient. All I remember is there was something that I found unexpected about the data.

**Comment by niharikasingh** [comment]
In my opinion, this would be a useful improvement. People could choose to write concise header-less tables if they preferred that.
