### ISSUE TITLE
Report: Suppress cucumber's own step failure reports?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#326]
Probably not a good idea, but they _are_ pretty messy compared to ours. Maybe we can hide them away in a file somewhere?

**Comment by BryceStevenWilley** [comment]
I think this was solved by putting cucumber's errors in the debug_log.txt, i.e. #491 and #544?

**Comment by plocket** [comment]
The question was whether to suppress them in the GitHub action console. Personally, I'm reluctant to do that. Maybe ever, but at least until we're much more sure our reports cover things much better.

**Comment by plocket** [comment]
There are reasons to keep them that I've seen now:
- Undefined steps
- Wrongly formatted tables

Unfortunately, I've seen other errors confuse users, so...
