### ISSUE TITLE
Allow downloading a file with the same name twice in a single scenario

### ISSUE THREAD

**Issue by niharikasingh** [SuffolkLITLab/ALKiln#357]
Right now, if we try to download a single file twice in the same scenario, the newer download overwrites the older download. I think what we need to somehow be able to specify `I download docassemble-filename.pdf as local-filename.pdf`. That way, both downloads will be saved properly. 

- [ ] Add a step `I download docassemble-filename.pdf as local-filename.pdf`
- [ ] Remove warning in `I download "([^"]+)"$` step that file can only be downloaded once per scenario 
- [ ] Have the test in `tests/features/interactive_steps.feature` download the same file twice in a scenario 

From https://github.com/plocket/docassemble-cucumber/pull/329

**Comment by plocket** [comment]
Different than #477, which is about whether we can download multiple files in one scenario at all.

**Comment by plocket** [comment]
This was a good thought for us to look into, but with feedback we're deciding that it's up to the developer to give files unique names - not a great practice to name two documents "petition.pdf" when one is actually just a preview document.
