### ISSUE TITLE
Allow numbers in safe filenames and report text

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#371]
Right now, scenario names get stripped of numbers when converting them to either of the above. Avoid stripping those out as they can be quite useful.

**Comment by niharikasingh** [comment]
The main place this conversion to safe filenames happens is in `getSafeScenarioFilename`, and there might be a few other scattered places.

**Comment by plocket** [comment]
I think this exercise has highlighted that there are a few concerns that need to be separated - the scenario id, the scenario report heading, and the scenario filename. I've made PR #463 on the current PR branch for this issue.

**Comment by plocket** [comment]
Closed by #463 and #476
