### ISSUE TITLE
When someone creates a tagged release, the tag can't be pulled into Docassemble's playground

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/ALKiln#380]
* Branches are the same as tags
* Tags can't be pulled into the playground

Idea: have a way to tell the testing script when it's a tag so that the script will test Main/whatever the default branch is 

Alternative: let DA pull in a tag. but would that even work unchanged w/ Docassemble? still might add additional menus or checkboxes that need to be handled. But maybe not if we switched everything to using an API key (but note that's a big refactor)

**Comment by plocket** [comment]
Quick sanity check: Does a tag release change any code other than the tag? If not, the code will have already been tested with a previous commit, right? Or are we looking to ensure that a tag release has a green checkmark?

I also wonder if a tag release counts as a push. If not, we can probably add it as a trigger. Either way, we can see whether the tests use the right branch automatically.

**Comment by nonprofittechy** [comment]
As far as I know a tag doesn't change code. The tag applies to an existing commit

**Comment by plocket** [comment]
We can work on researching this topic, but I'm still not quite clear on the need being expressed in this situation. If a tag doesn't change code, what is the goal in testing the tag? Is it currently causing errors? If so, do you have a link to one?

**Comment by nonprofittechy** [comment]
As far as I can recall these are notes from a Monday call as what we decided to try to reduce false positive tests failures. The issue is every time we bump version it creates a test failure. It would be fine to just not test tags, or have an option in the bump version script that prevents the test from happening.

We just want to avoid boy who cried wolf issues here. Frequent false alerts make the tests less helpful and can be a bit overwhelming on ones inbox.

**Comment by plocket** [comment]
Interesting note on this process so others don't have to search for it:

In the `Run echo "REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> $GITHUB_ENV` step of a tag test (e.g. https://github.com/SuffolkLITLab/docassemble-AssemblyLine/runs/4448559745?check_suite_focus=true), I can see the environment variables and they do indeed contain a branch name. In this case, `refs/heads/349_alkiln_update`. The problem might be when that PR branch is deleted before the tag version gets to run its test after merging with main.

I think we still might want to go with disabling testing for tag versions if we can.

Here are some docs on ignoring things on push, including tags: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-ignoring-branches-and-tags. We can probably use `tags-ignore:` with a wildcard (`*`) to catch all of them.

**Comment by plocket** [comment]
This will need to be changed in [the workflow file of our setup interview](https://github.com/plocket/docassemble-ALAutomatedTestingTests/blob/7f476adbd0d677368a55c963b4c3581f1d504872/docassemble/ALAutomatedTestingTests/data/questions/al_testing_files_to_push.yml#L110), as well as in the Projects that already have their workflows installed. These will need to be changed soon anyway, so this should be part of the v4 milestone changes.

**Comment by plocket** [comment]
I think I was off on this one. A good learning experience. This currently ignores pushes that have a tag ref that matches the pattern, not just the tag push itself. This is [a way to do it with travis](https://github.com/travis-ci/travis-ci/issues/8051#issuecomment-335517982). Will edit this comment when I find more info on how to do it without travis.

**Comment by plocket** [comment]
And yet now it's running again. I can't spot what's changed. We can wait and see, I suppose.

**Comment by plocket** [comment]
This seems to be working now, so I suppose [`tags-ignore:` for the GitHub workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#example-excluding-branches-and-tags) was the right move. Not sure why things stopped running for a while.
