### ISSUE TITLE
Meta: How do we connect issues on the kiln-testing-interviews da repo to this repo so we can keep track of those tasks too?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#397]
And is there a way to automate it?

**Comment by BryceStevenWilley** [comment]
I think we need to transfer older testing specific issues from https://github.com/SuffolkLITLab/docassemble-ALKilnSetup/issues to here, and then we'll be good. I'll do that now!

**Comment by plocket** [comment]
Transferred and moved tests into this repo! Thanks @BryceStevenWilley!
