### ISSUE TITLE
Add cucumber test output to the end of the report

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#398]
I think that `err` will appear in the cucumber output, though I do wish we had a better way to test that.

In our convo, we brought up that the cucumber output may be at times useful for a different set of users, so maybe that should be included at the bottom of the report file somehow.

Also, the pros and cons of having the both more detailed and less detailed cucumber output in place of the report. Cucumber gives output such as `expected x to exist, but it did not` and then the stack trace. That isn't usually helpful for people trying to understand why their interview failed. The stack trace just traces the ALKiln code and is a red herring, and the failure reason is often not specific enough about what went wrong with the interview itself.

_Originally posted by @plocket in https://github.com/SuffolkLITLab/ALKiln/pull/391#discussion_r764081000_

**Comment by BryceStevenWilley** [comment]
I think this is a duplicate of #491, where more is being done there.

**Comment by plocket** [comment]
I think you're right. Closing in favor of #491 - put cucumber info in debug_log.txt.
