### ISSUE TITLE
How do I disable?

### ISSUE THREAD

**Issue by michaelhofrichter** [SuffolkLITLab/ALKiln#433]
Is there a way to disable the tests or remove the automatic actions? I can change the github secrets, but that is still going to trigger the actions. Until #425 is resolved, I think I've got to disable the testing for now.

**Comment by plocket** [comment]
Yes, you can disable actions in GitHub.

For an organization:
https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#managing-github-actions-permissions-for-your-organization

For a repository:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#managing-github-actions-permissions-for-your-repository

I'll make this into a documentation issue too, thanks!

**Comment by plocket** [comment]
You can also keep your other actions running and disable just that workflow: https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow.

Feel free to close if this resolves the question.

**Comment by plocket** [comment]
These methods are now documented at https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing#disable-the-tests. Feel free to re-open if you see that there's more to be done here.
