### ISSUE TITLE
Moving Packages

### ISSUE THREAD

**Issue by michaelhofrichter** [SuffolkLITLab/ALKiln#443]
If I end up transferring a package that has ALKiln enabled from my ownership to an organization's ownership what settings need to be updated? Do I just need to adjust the references in `package.json` to point to the new owner? 
Thanks,

**Comment by plocket** [comment]
If it just gets transferred to a GitHub organization, I can't think of a problem that would arise. You can update the `package.json` repo info too - that's good practice - but I can't think of a way it could impact the tests. The tests get info about your GitHub repo from your workflow file in `.github/workflows`, so it stays up to date with whatever's going on with that repo. That does all the GitHub parts of the testing. It doesn't use the `package.json` for that kind of stuff.

If the server changes, then you need to update your GitHub secrets - SERVER_URL, PLAYGROUND_ID, etc. - or set those as organization secrets and then delete your repository's secrets. If your tests use a current version of ALKiln, you should be able to use the [ALKiln setup interview](https://apps-dev.suffolklitlab.org/start/test-setup/) to get the right info into files of the repo again. It will replace the contents you have in them now. All the other tests you've written will stay happy. The setup interview might also work if you're behind, but you can check with us about that first if you're not excited to experiment in that way.
