### ISSUE TITLE
url_args

### ISSUE THREAD

**Issue by michaelhofrichter** [SuffolkLITLab/ALKiln#449]
Is there a way to try starting an interview while passing specific url arguments? 
instead of 
`Given that I start the interview at "caller"` 
is there a way to say 
`Given that I start the interview at "caller&phone=111-111-1111"`?

**Comment by plocket** [comment]
Whatever you put in those quotes is put at the end of the Project's url. If you include ".yml" (e.g. "caller.yml") and then the params, I _think_ that should work.

We should try it ourselves. We'll have to figure out what params we can set that would have a detectable impact on the page.

**Comment by michaelhofrichter** [comment]
That doesn't work. I'll send you my logs so you can see for yourself. 
Is there a way to save the variable file to the error log so that I can see if a url_arg got set?

**Comment by plocket** [comment]
There's not currently a way to save the JSON variables. I do think I've found the problem, though, so thanks for the info. The interview name processing was making too strict an assumption about where the string `.yml` would be. Making a hotfix for it now.

**Comment by plocket** [comment]
Implementing for v4 now.

**Comment by plocket** [comment]
Apparently already implemented there too! Huzzah! Thank you to past me 👍
