### ISSUE TITLE
Step: Allow devs to download the JSON variables of an interview

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#454]
We may have to adjust how downloading artifacts works so the action just downloads a folder will all the artifacts instead of individual files.

We might be able to do this with the API, but we could do this straight in a puppeteer `.evaluate()` or something using a built in docassemble javascript function that makes an ajax request: https://docassemble.org/docs/functions.html#js_get_interview_variables.

~Right now it's not behaving asynchronously, which is a bit crazy.~ Fixed

**Comment by plocket** [comment]
We need this for some developer debugging on a private repo at the moment, so I'm going ahead with it while other stuff is waiting in the pipeline.

**Comment by plocket** [comment]
Not sure what the best way is to store this info. A separate document for each JSON object? One document that contains all of them? In the report? What would help differentiate the different objects from each other?

Do you have thoughts, @michaelhofrichter?

**Comment by nonprofittechy** [comment]
One separate file for each step, in the same place other output documents are stored.

**Comment by plocket** [comment]
[The below was misplaced from another issue that's now closed.]

From discussion:

- File path name length is the actual filename length problem, so reduce the length of the filename even more (50 chars in total is one nonprofittechy uses)
- Timestamp is the easy way
- Possibly type of file in the beginning maybe for type of file description.

~An idea: Maybe only timestamp in scenario folder name?? But then inside the folder things wouldn't be ordered by their sequence, but by their alphabetical name instead.~ So maybe we should keep type of file and then name, but make type of file shorter, like 'pic' or 'img' instead of 'screenshot'. Not sure what we should do for 'download'.

**Comment by BryceStevenWilley** [comment]
I think this is resolved? https://github.com/SuffolkLITLab/ALKiln/pull/498 says "Addresses", and the last comment I think belongs on a different issue. I'm gonna close this, since I think GitHub just didn't automatically link these.
