### ISSUE TITLE
Add a "log" file so there'll be an artifact even if the tests are ended early

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#466]
[Conclusion: Just for v4. Add a "log.txt" file where each report entry is saved as it happens. Upload that as a GitHub artifact at the end.]

That way if they see something failed and want to stop, they'll have something, even if it's slightly more messy. What do folks think? [Do this automatically? Do this only when dev requests it? If the latter, we can't do this for setup and takedown.]

[Include setup and takedown in the logs.]

I wish we could record everything that's logged to the console as well as all our report messages, but I'm not sure we can. See other issues about cucumber's output.

Should we be as verbose as possible in these logs, even logging our own debugging stuff, or should we stick with just stuff that would go in reports?

**Comment by plocket** [comment]
I say we stick with report items and talk about debug logs later.

**Comment by mcdonaldcarolyn** [comment]
https://stackoverflow.com/a/41233011

**Comment by plocket** [comment]
Closed by #517!
