### ISSUE TITLE
Test: reports for file upload errors

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#482]
- [x] The specified files don't exist in the discovered directory
- [x] ~None of the specified files are in the discovered directory~ We're going to remove this error in #483.

**Comment by harshlancer** [comment]
Hey, @plocket I will love to contribute. Can you tell me about it?

**Comment by plocket** [comment]
Hi, @harshlancer, it'd be great to have you on board! Just fyi, the other issue you commented on is a lot more simple to deal with - good find - so look at that one before this one gets you down.

As a disclaimer, this issue requires some setup. We're experimenting with the 'good first issue' label, using it for people who know the technologies, but don't need to be super familiar with our existing codebase.

You're our first test case and now that I actually have to put this all in writing, this issue seems like a lot to put on someone new. At the very least, you've helped us think about this process, and this particular issue, more carefully. Now that I'm reading the items again, I think you can probably only create the second test at the moment, but even that would be valuable.

If that's something you have bandwidth for, read on.

How I think we/you would do this:
1. We would first make you a member on this repository.
3. You could look a [test that already uploads files](https://github.com/SuffolkLITLab/ALKiln/blob/482_v3_test_upload_file_errors/tests/features/interactive_steps.feature#L7-L12) to copy that part of it.
2. You could then go to [this link to edit the "reports.feature" file](https://github.com/SuffolkLITLab/ALKiln/edit/482_v3_test_upload_file_errors/tests/features/reports.feature) in a new branch I just created called 482_test_upload_file_errors and add this new test at the bottom.
3. Use a couple filenames that don't exist in our ["tests/features"](https://github.com/SuffolkLITLab/ALKiln/tree/482_v3_test_upload_file_errors/tests/features) folder. Something like "wrong_file_1.png".
4. Add two steps right under `Scenario`:
```
  Given the final Scenario status should be "failed"
  Given the Scenario report should include:
  """
  Could not find
  """
```
6. When you save the file, its tests will run on it automatically. They'll probably fail for a while until you get more familiar with Steps, or if my instructions are really bad.
5. Experiment a bit and see how it goes.

If you run into problems, ask us questions. If you want to chat live, come to the [docassemble Slack workspace](https://join.slack.com/t/docassemble/shared_invite/zt-ohrn8y9z-_Fb3RAl~JPBU6Km7odBPfQ) (you can do it online) and go to the #assembly-line-tests channel. It's quiet there now because most of our conversations happen on Teams chat now, but I'll get the message.

SuffolkLITLab's goals for the broader project are to help make court forms easier for non-lawyers - things like restraining orders and preventing evictions that have been big problems during this pandemic. You can see a lot of technical details about how we're trying to help lawyers do that at https://suffolklitlab.org/docassemble-AssemblyLine-documentation.

This part of the project, ALKiln, has technical documentation at https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing.

If you're interested in going deeper, we can help you so more set up so you don't have to edit on GitHub. Fair warning, it's a bit of a process.

**Comment by plocket** [comment]
Here's an invitation to be a collaborator: https://github.com/SuffolkLITLab/ALKiln/invitations

**Comment by plocket** [comment]
Let me know if there are any problems 👍
