### ISSUE TITLE
npm publish (when automated) - ensure our pre-releases don't get pulled with `npm install @suffolkLITLab/alkiln`

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#502]
[Ignore the comments below this one. I've been commenting in the wrong issue.]

[Closing this. The solution is to always publish pre-releases with a tag other than `latest`. For example, `dev` or `feat` or `logs` or something else relevant.]

This isn't too important to us because of the way we're setting up everyone's repos for them, but we should take care of this at some point. Also, right now this is mostly a note for me as I'm the one publishing things, especially pre-releases, but if we automate, then we'll need to account for this.

npm tags your most recently published version with `latest`, even if it's a prerelease. That means `npm install`ing our package without any version number may install prereleases. Again, I don't know why anyone would be installing our package that way, but it'd be following good practices at the very least.

See how to do this when publishing at https://docs.npmjs.com/cli/v8/commands/npm-dist-tag.

**Comment by plocket** [comment]
We might want to push tags to GitHub depending on what we do with [freezing the package-lock.json](https://github.com/SuffolkLITLab/ALKiln/issues/614#issuecomment-1244733632).

We might be able to at least use this action that outputs the release number: https://github.com/MeilCli/bump-release-action/blob/master/README.md#output.

We also need to use the output to :
1. Update the developer's package.json and package-lock.json. How do we do this? It has to come before the action (so the changes get published to npm with the bump), but the packages have to use the same version as the action creates. Maybe we can feed in a specific version to the action manually after having created it for the files. Prone to error, but what else can we do? Is it possible to automate? We then do the action, adding its commits to the specific branch where we updated those files? [Maybe look into the 'files' section (under the [bump section](https://github.com/MeilCli/bump-release-action#bump) since files link doesn't work). I don't think it'll handle installing the package, though, to create package-lock.json.]
3. Push the new GitHub tag. The bump action might have this built in. See `tag-prefix` in their bump.yml in the README. It seems to want to push to a new branch that can make a PR. Maybe that's the best way to go. Not sure how it lines up with npm, especially if it doesn't get merged.
4. Ideally, update the CHANGELOG. Probably before the action so it can be part of the same commit. Maybe it's possible to do this with some clever string manipulation, though only if people are consistent with how they write the changelog, which seems very fragile. Read more below about why we'd want to do it at the same time.

I'm not sure what we'll do about the changelog because its new version entry really shouldn't be fully filled out without knowing the npm version at the same time or mistakes and confusion might ensue. I wish we could use the changelog to control what version is published. If anyone has ideas or can find a solution, that could be a good bonus.

On the other hand, maybe our tag commits will be our changelog, though we'll lose the benefit of all the past changelogs. Can they be multi-line? Detailed? Have links? Do you know anything about this @BryceStevenWilley ?

Experiments:
- Can we have a multiline commit/tag message when we run this action? (to act as a changelog)
- Is it possible to add this as a commit to a pre-existing branch (where we'd have updated the developer's files)?
- (may not need this  info, so not a priority right now) Is it possible to push to the default branch instead of a non-default branch?

**Comment by plocket** [comment]
https://github.com/MeilCli/bump-release-action doesn't have a lot of stars and I can't see how many people are using it. I'm looking at their marketplace page too: https://github.com/marketplace/actions/bump-version-and-publish-release-action. It seems to have a ton of commits, though, and have a few more recent commits. We can try looking for another one...

**Comment by plocket** [comment]
I've gotten some feedback from a place:
- a package lock is dev-only
- a package’s consumers don’t use the lockfile
- a package should ALWAYS use ranges

I'm not sure if "a package’s consumers don’t use the lockfile" means that it's impossible or just that it's generally not a good idea. Is this endeavor possible?

**Comment by plocket** [comment]
Apparently you can't publish to npm through an action anymore because of two-factor authentication... I guess we may need a script to run locally instead. Any other ideas?

**Comment by BryceStevenWilley** [comment]
The scope of this is a bit bigger than I had anticipated; I hadn't thought that we would make the action change code at all, that it would just take an existing commit and package / publish it, and make a Github release. Still might be all doable, but just a lot more than I thought, and would required IMO a bit more testing to make sure the action works as anticipated.

https://github.com/MeilCli/bump-release-action seems like a decent package, the developer is responsive to the few issues they've had on the repo. I don't think stars is a great metric to lean on.

> I've gotten some feedback from a place: a package lock is dev-only

Looking back through old discussions, it looks like [shrinkwrap](https://docs.npmjs.com/cli/v8/configuring-npm/npm-shrinkwrap-json) is what we want: it is explicitly for publishing, so none of the feedback from your source applies, since I think that feedback is mostly for publish packages as libraries, not as a separate application, like we are. I think we've had this discussion before, in https://github.com/SuffolkLITLab/ALKiln/discussions/532.

> Apparently you can't publish to npm through an action anymore because of two-factor authentication

Is that something you directly ran into, or something you heard about, I can't tell from the comment? From https://docs.npmjs.com/about-two-factor-authentication, we should be able to set 2FA to `admin` only, so we can still publish packages without need 2FA.

**Comment by plocket** [comment]
Actually relevant to this specific issue (some above are in the wrong issue): Closing this. The solution is to always publish pre-releases with a tag other than `latest`. For example, `dev` or `feat` or `logs` or something else relevant.
