### ISSUE TITLE
Can't take screenshot of signature pages

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#511]
It causes an error because taking a screenshot erases the signature. This is technically a bug, but not one that's urgent so I'm going to avoid derailing us by leaving off that label. We can't think of a reason anyone other than us would want to take a screenshot of the signature page. It's going to be documented with https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/issues/212.

More details:

Docassemble currently handles signatures in-house, but hasn't accounted for the page zooming in and out, [which clears the drawing in the canvas](https://stackoverflow.com/questions/53263526/canvas-drawing-disappears-on-zoom-in-out/53275532). When kiln takes a screenshot, it uses the "full page" feature of puppeteer, which seems to zoom out on the page to get the whole thing in the viewport. That causes the signature to be erased.

A potential solution for the future is to take screenshots differently on signature pages [- don't take a full page screenshot]. That might be problematic if developers are trying to find out things about the page that are off-screen, though. An upstream fix is probably necessary, so we might focus on that instead. The code is [near the beginning of app.js](https://github.com/jhpyle/docassemble/blob/fdfff85381454fa2dbc44ed869b431cf4a3a4269/docassemble_webapp/docassemble/webapp/static/app/app.js#L105).

**Comment by BryceStevenWilley** [comment]
Note; documented in https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/282

**Comment by plocket** [comment]
Closed by https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/282

**Comment by plocket** [comment]
Wasn't closed. Not sure why I did that. It was just documented. [Not sure how to get rid of the link to the PR, dangit.]

**Comment by plocket** [comment]
I think we can deal with this by listening to a window `resize` or `orientationchange`, then re-drawing after the event.

**Comment by plocket** [comment]
Alternatively, when taking a screenshot we can try to determine if it's a signature page and, if so, don't use the 'full screen' option.

**Comment by plocket** [comment]
Adjusted suffolk documentation to remove warnings about this bug.
