### ISSUE TITLE
Look at suspicious looking backticks inside backticks

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#516]
[The code seems to be working, so I'm] not sure how to test this, but this line in our code makes me nervous:

https://github.com/SuffolkLITLab/ALKiln/blob/bd07645ed8a39c60e6ba65761481e702e229efe5/lib/scope.js#L955

I'm specifically suspicious of the backticks here:
```js
`['"]`
```
Do they not escape the outer backticks? My code highlighter doesn't show the value inside those backticks as a string...

**Comment by BryceStevenWilley** [comment]
[Nested template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#nesting_templates) are fine. There's an argument to be made for separating it, but IMO for something this small it's not worth it, especially when it would involve adding more escapes for the quotes trying to be matched.
