### ISSUE TITLE
Takedown script for deleting the language files

### ISSUE THREAD

**Issue by niharikasingh** [SuffolkLITLab/ALKiln#64]
Right now, takedown leaves the language files untouched

**Comment by plocket** [comment]
My thought is to make a `lang_takedown` functionality and that could be used in `takedown`. That way a local dev can delete the languages without taking down the project.

I know it's a bit weird that they stick around after the tests, I just imagine a situation where I as the developer want to examine more closely what's happening with a specific language.

**Comment by plocket** [comment]
We no longer use the language files workaround.
