### ISSUE TITLE
Discuss how to keep dependent repos up to date

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#9]
- Add workflow to make PR with latest package version?

**Comment by plocket** [comment]
Surely there's a bot that lets you send out a suggested update?

**Comment by plocket** [comment]
We can now at least see the dependents that use our repo: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository#dependents-view

**Comment by BryceStevenWilley** [comment]
To expand more on this: 
* we can see [our Github Action dependents now](https://github.com/SuffolkLITLab/ALKiln/network/dependents?package_id=UGFja2FnZS0yOTcwMTQwMTUx)! 
* If I understand correctly, [dependabot should work automatically for GitHub actions](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#github-actions), without us having to do anything else? We'd have to check [from dependency, going to the insights/dependabot tab](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/listing-dependencies-configured-for-version-updates#viewing-dependencies-monitored-by-dependabot).

I think dependabot is the right way to go about it, even though there's some config all of our users have to set up.
